version: '3'

volumes:
  pg_data_prod:
  static_vol:
  media_vol:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
      
  backend:
    image: nesterovv89/foodgram_backend
    depends_on:
      - db   
    env_file: .env
    volumes:
      - static_vol:/app/collected_static/
      - media_vol:/app/media/

  frontend:
    env_file: .env
    depends_on:
      - backend
    image: nesterovv89/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_vol:/frontend_static

  gateway:
    image: nesterovv89/foodgram_gateway
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_vol:/var/html/static/
      - media_vol:/var/html/media/
    depends_on:
      - backend
    container_name: foodgram-gateway-1
    ports:
      - 8010:80
